name: Test
on:
  push:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
jobs:
  test:
    strategy:
      matrix:
        go-version:
          - 1.16
          - 1.17
          - 1.18
          - tip
        include:
          - may-fail: false # Default
          - go-version: tip # tip version may fail
            may-fail: true
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    continue-on-error: ${{ matrix.may-fail }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
      - name: Test with ${{ matrix.go-version }} on ${{ matrix.os }}
        run: go test -v -race -coverprofile=coverage ./...
      - name: Coveralls integration
        uses: shogo82148/actions-goveralls@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-profile: coverage
          parallel: true
          flag-name: ${{ matrix.go-version }}-${{ matrix.os }}

  # Call parallel build Webhook
  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: shogo82148/actions-goveralls@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true